### PR TITLE
Add a DCP file to test NetTools.isGlobalClock()

### PR DESCRIPTION
**Pull request by WenhaoLin-AMD**
Add a DCP file based on Versal xcvp1002 device to test `NetTools.isClockNet()`. 

This simple design contains two groups of LED outputs. Each LED output group is controlled by a clock and a reset signal. Two constraints are added to ensure that, after this design is implemented on Versal FPGA device, the corresponding clock net and reset net will be driven by a BUFGCE site and a BUFG_FABRIC site accordingly.

Some designs in FPGA '24 contest benchmarks are re-generated/re-implemented on Versal architecture. In the post-implemented results of these designs, the nets with the type GLOBAL_CLOCK are all driven by BUFGCE and BUFG_FABRIC sites. That's why the two_clk_check_NetTools.dcp design can tells whether NetTools.isClock(Net net) works correctly on Versal architecture.

This design is created for the test in https://github.com/Xilinx/RapidWright/pull/1057

### CODE REVIEW

**Comment by WenhaoLin-AMD** [comment]
The EDIF file has been inserted into the DCP file now.

**Comment by WenhaoLin-AMD** [comment]
> The EDIF file has been inserted into the DCP file now.

Sorry that I haven't added the BUFG_FABRIC case. Need further updates.

**Comment by eddieh-xlnx** [comment]
Thanks! Can you add edit the first comment and add a brief description of what's in this DCP? I'd like to see the `NetTools` PR created and passing with this DCP before I merge it in.

**Review by eddieh-xlnx — COMMENTED** [review]
Thanks! Can you add edit the first comment and add a brief description of what's in this DCP? I'd like to see the NetTools PR created and passing with this DCP before I merge it in.

**Comment by WenhaoLin-AMD** [comment]
> Thanks! Can you add edit the first comment and add a brief description of what's in this DCP? I'd like to see the NetTools PR created and passing with this DCP before I merge it in.

Sure. This simple design contains two groups of LED outputs. Each LED output group is controlled by a clock and a reset signal. Two constraints are added to ensure that, after this design is implemented on Versal FPGA device, the corresponding clock net and reset net will be driven by a BUFGCE site and a BUFG_FABRIC site accordingly.

I re-generated some designs in FPGA '24 contest benchmarks and looked into the nets with the type `GLOBAL_CLOCK`. All these nets are driven by BUFGCE and BUFG_FABRIC sites. That's why the `two_clk_check_NetTools.dcp` design can tells whether `NetTools.isClock(Net net)` works correctly on Versal architecture.

**Review by eddieh-xlnx — APPROVED** [review]

**Pull request merged**
